<a href="https://colab.research.google.com/github/vyshali2419/AI-code-lab-3/blob/main/AIAC_lab_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def filter_negative_numbers(input_list):
  """
  Filters out negative numbers from a given list.

  Args:
    input_list: A list of numbers.

  Returns:
    A new list containing only the non-negative numbers from the input list.
  """
  return [number for number in input_list if number >= 0]

# Example usage:
my_list = [1, -2, 3, -4, 5, 0, -6]
filtered_list = filter_negative_numbers(my_list)
print(f"Original list: {my_list}")
print(f"Filtered list: {filtered_list}")

Original list: [1, -2, 3, -4, 5, 0, -6]
Filtered list: [1, 3, 5, 0]


First, let's create a dummy text file for demonstration purposes.

In [ ]:
# Create a dummy text file
with open("sample.txt", "w") as f:
  f.write("This is a sample text file.\n")
  f.write("This file is for demonstrating word frequency counting.\n")
  f.write("This is the end of the sample file.")

Now, let's write the code to read the text file and count the frequency of each word.

In [ ]:
from collections import Counter
import re

def count_word_frequency(filename):
  """
  Reads a text file and counts the frequency of each word.

  Args:
    filename: The name of the text file.

  Returns:
    A dictionary where keys are words and values are their frequencies.
  """
  with open(filename, 'r') as f:
    text = f.read().lower()  # Read the file and convert to lowercase
    words = re.findall(r'\b\w+\b', text) # Find all words using regex
    word_counts = Counter(words) # Count word frequencies

  return word_counts

# Example usage:
filename = "sample.txt"
word_frequencies = count_word_frequency(filename)
print(f"Word frequencies in '{filename}':")
for word, count in word_frequencies.items():
  print(f"{word}: {count}")

Word frequencies in 'sample.txt':
this: 3
is: 3
a: 1
sample: 2
text: 1
file: 3
for: 1
demonstrating: 1
word: 1
frequency: 1
counting: 1
the: 2
end: 1
of: 1


In [ ]:
class Book:
  """Represents a book with title and author."""

  def __init__(self, title, author):
    """Initializes a new Book instance."""
    self.title = title
    self.author = author

  def summary(self):
    """Prints the title and author of the book."""
    print(f"Title: {self.title}")
    print(f"Author: {self.author}")

# Example usage:
my_book = Book("The Hitchhiker's Guide to the Galaxy", "Douglas Adams")
my_book.summary()

Title: The Hitchhiker's Guide to the Galaxy
Author: Douglas Adams


# Task
Write a program that checks whether a number is an Armstrong number.

## Generate armstrong number checking code

### Subtask:
Write Python code to check if a given number is an Armstrong number.


**Reasoning**:
I need to write a Python function to check if a number is an Armstrong number according to the provided steps.



In [ ]:
def is_armstrong_number(number):
  """
  Checks if a number is an Armstrong number.

  Args:
    number: An integer.

  Returns:
    True if the number is an Armstrong number, False otherwise.
  """
  # Convert the number to a string to get the number of digits
  num_str = str(number)
  num_digits = len(num_str)
  sum_of_powers = 0

  # Iterate through each digit
  for digit in num_str:
    # Convert digit back to integer and raise to the power of num_digits
    sum_of_powers += int(digit) ** num_digits

  # Compare the original number with the calculated sum
  return number == sum_of_powers

# Example usage:
test_number = 153
if is_armstrong_number(test_number):
  print(f"{test_number} is an Armstrong number.")
else:
  print(f"{test_number} is not an Armstrong number.")

test_number_2 = 123
if is_armstrong_number(test_number_2):
  print(f"{test_number_2} is an Armstrong number.")
else:
  print(f"{test_number_2} is not an Armstrong number.")

153 is an Armstrong number.
123 is not an Armstrong number.


## Explain armstrong number concept

### Subtask:
Provide a brief explanation of what an Armstrong number is.


**Reasoning**:
Provide a brief explanation of what an Armstrong number is and include an example.



In [ ]:
# Create a markdown cell with the explanation and example
get_ipython().run_cell_magic('markdown', '', """
## What is an Armstrong Number?

An Armstrong number (also known as a narcissistic number, pluperfect digital invariant, or happy number) is a number that is the sum of its own digits each raised to the power of the number of digits in the number.

For example, 153 is an Armstrong number because:
- It has 3 digits.
- $1^3 + 5^3 + 3^3 = 1 + 125 + 27 = 153$.

Since the sum of the cubes of its digits is equal to the original number, 153 is an Armstrong number.
""")


## What is an Armstrong Number?

An Armstrong number (also known as a narcissistic number, pluperfect digital invariant, or happy number) is a number that is the sum of its own digits each raised to the power of the number of digits in the number.

For example, 153 is an Armstrong number because:
- It has 3 digits.
- $1^3 + 5^3 + 3^3 = 1 + 125 + 27 = 153$.

Since the sum of the cubes of its digits is equal to the original number, 153 is an Armstrong number.


## Summary:

### Data Analysis Key Findings

*   The Python code correctly implements the logic to check if a number is an Armstrong number by summing the digits raised to the power of the number of digits.
*   The code successfully identifies 153 as an Armstrong number and 123 as not an Armstrong number.
*   An Armstrong number is defined as a number that is the sum of its own digits, each raised to the power of the total number of digits in the number.
*   The example of 153 ($1^3 + 5^3 + 3^3 = 153$) clearly illustrates the definition of an Armstrong number.

### Insights or Next Steps

*   The implemented function can be used to check any integer for the Armstrong property.
*   The explanation provides a clear understanding of the concept behind Armstrong numbers.


In [ ]:
list_of_dicts = [
    {'name': 'Alice', 'age': 30},
    {'name': 'Bob', 'age': 25},
    {'name': 'Charlie', 'age': 35},
    {'name': 'David', 'age': 25}
]

# Sort the list of dictionaries by 'age'
sorted_list = sorted(list_of_dicts, key=lambda x: x['age'])

print("Sorted list by age:")
for item in sorted_list:
  print(item)

# You can also sort by other keys, for example 'name'
sorted_list_by_name = sorted(list_of_dicts, key=lambda x: x['name'])

print("\nSorted list by name:")
for item in sorted_list_by_name:
  print(item)

Sorted list by age:
{'name': 'Bob', 'age': 25}
{'name': 'David', 'age': 25}
{'name': 'Alice', 'age': 30}
{'name': 'Charlie', 'age': 35}

Sorted list by name:
{'name': 'Alice', 'age': 30}
{'name': 'Bob', 'age': 25}
{'name': 'Charlie', 'age': 35}
{'name': 'David', 'age': 25}
